export {default as Home} from "./Home"
export {default as LogIn} from "./LogIn"
export {default as NotFoundPage} from "./NotFoundPage"
export {default as Dashboard} from "./Dashboard"
export {default as SignUp} from "./SignUp"